# Generated by Django 2.0.1 on 2018-02-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180208_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='Início'),
        ),
    ]
